
query_reader:
  _target_: code.utils.ris_breg_reader.ESQueryReader
  queries: queries.tsv
  collection_prob_dict_file: term_p.json
  kw_extractor: plm
  query_term_ratio: 0.9
  smooth_factor: 0.2
  filter: true


tokenizer:
  _target_: code.preprocessing.brise_tokenizer.RisBregTokenizer
  spacy_model_name: de_core_news_md


retrieval:
  runs_dir: runs/brise
  run_name: es
  size: 100
  agg_size:
  rank_aggregation: