query_reader:
  _target_: code.utils.cord19_reader.ESQueryReader
  queries: topics-rnd5.xml
  index_fields: 
    - title
    - section
    - paragraph_text

retrieval:
  run_name: es_paragraphs
  size: 1000
  agg_size: 100
  rank_aggregation:
    _target_: code.evaluation.eval.agg_paragraphs_recip