query_reader:
  _target_: code.utils.cord19_reader.ESQueryReader
  queries: topics-rnd5.xml
  index_fields: 
    - title
    - abstract

retrieval:
  runs_dir: runs/cord19
  run_name: es_doc
  size: 100
  agg_size: 100
  rank_aggregation: 
    _target_: code.evaluation.eval.agg_remove_duplicates