config:
  root_dir: ??? # the root directory of the whole data set base
  input_docs_dir: cord19/cord-19_2020-07-16/document_parses/pdf_json #original json files for cord19 doc collection path
  metadata_path: cord19/cord-19_2020-07-16/metadata.csv #the full path of the metadate csv file
  working_dir: cord19/cord-19_2020-07-16/working #the directory of intermediate processing and results
  output_dir: cord19/cord-19_2020-07-16/output #the output directory of retrieval results
  lang: 'en'

collection_normalization:
  out_dir: cord-19_2020-07-16__pdf_json__normalized

representation:
  bow_working_dir: cord-19_2020-07-16__bow_working
  bow_output: cord-19_2020-07-16__bow_out
  tfidf_working_dir: cord-19_2020-07-16__tfidf_working
  tfidf_output: cord-19_2020-07-16__tfidf_out


clustering:
  out_dir: cord-19_2020-07-16__pdf_json__normalized__clusters

delta:
  normalized_delta_path: cord19_normalized_delta.json #output path of document similarity
  base_retrieval_path: ??? #json file for baseline retrieval which is set per run

retrieval:
  rerank_path: ??? #the json file of the reranking result which is set per run
  run_name: ??? #run name which is set per each run
  qrel_id_field: cord_uid

dtc: # dynamic test collection information
  evaluation_splits_dir: cord19/cord-19_2020-07-16/dtc #the output directory of retrieval results
  evaluation_splits_path: ??? # hdf5 file of samples and evaluation data.
  docs_full_info_path: TREC-COVID_date_p2.csv
  docno_date_path: TREC-COVID_docno_date.csv
  out_in_fields_map: {"docno": 'cord_uid', "date": 'date_final'}
  dtc_evolving_cont_ids_path: TREC-COVID_dtc_evolving_cont_corduids.pkl
  dtc_evolving_ids_path: TREC-COVID_dtc_evolving_corduids.pkl
  dtc_random_ids_path: TREC-COVID_dtc_random_corduids.pkl
  dtc_evolving_cont_content_dir: TREC-COVID_dtc_evolving_cont
  dtc_evolving_content_dir: TREC-COVID_dtc_evolving
  dtc_random_content_dir: TREC-COVID_dtc_random
  full_contents_path: TREC-COVID_complete_content.csv
  start_step: 2
  end_step: 10
  epochs: 41
  generate_vocab_stats: True
