config:
  root_dir: ??? # the root directory of the whole data set base
  lang: 'en'

dtc: # dynamic test collection information
  evaluation_splits_dir: robust/dtc #the output directory of retrieval results
  evaluation_splits_path: ??? # hdf5 file of samples and evaluation data.
  docs_full_info_path: qrels_merge-robust.csv
  docno_date_path: Robust_docno_date.csv
  out_in_fields_map: { "docno": 'docno', "date": 'date1' }
  dtc_evolving_cont_ids_path: Robust_dtc_evolving_cont_docnos.pkl
  dtc_evolving_ids_path: Robust_dtc_evolving_docnos.pkl
  dtc_random_ids_path: Robust_dtc_random_docnos.pkl
  dtc_evolving_cont_content_dir: Robust_dtc_evolving_cont
  dtc_evolving_content_dir: Robust_dtc_evolving_all
  dtc_random_content_dir: Robust_dtc_random
  full_contents_path: qrels_merge-robust.csv
  n_evee: 40 # number of EE to create
  evee_overlap: 10 # the percentage of overlap between EEs
  evee_info_path: evee_docnos_40_10.pkl

  index:
    index_path: pyterrier_index # directory to store the index in

  evaluation:
    evaluation_perquery_output_path: evaluation_per_query # dir will contain tsv files of the retrieval results per query
    evaluation_mean_output_path: evaluation_mean #dir will contain tsv files of the average retrieval results
    rd_absolute_perquery_path: rd_absolute_perquery_path #dir contain the absolute rd per query
    rd_absolute_mean_path: rd_absolute_mean_path #dir contain the absolute rd of the mean
    rd_relative_perquery_path: rd_relative_perquery_path #dir contain the relative rd per query
    rd_relative_mean_path: rd_relative_mean_path #dir contain the relative rd of the mean


retrieval_models:
  - 0:
      run_name: tfidf
      model: TF_IDF
  - 1:
      run_name: bm25
      model: BM25
  - 2:
      run_name: pl2
      model: PL2
  - 3:
      run_name: dlm
      model: DirichletLM
  - 4:
      run_name: dlh
      model: DLH
  - 5:
      run_name: dph
      model: DPH
  - 6:
      run_name: tfidf_qe
      model: TF_IDF
      controls:
        qe: on
        qemodel: Bo1
  - 7:
      run_name: bm25_qe
      model: BM25
      controls:
        qe: on
        qemodel: Bo1
  - 8:
      run_name: pl2_qe
      model: PL2
      controls:
        qe: on
        qemodel: Bo1
  - 9:
      run_name: dlm_qe
      model: DirichletLM
      controls:
        qe: on
        qemodel: Bo1
  - 10:
      run_name: dlh_qe
      model: DLH
      controls:
        qe: on
        qemodel: Bo1
  - 11:
      run_name: dph_qe
      model: DPH
      controls:
        qe: on
        qemodel: Bo1

evaluation_metrics:
  - map
  - bpref
  - ndcg
  - Rprec
  - recip_rank
  - ndcg_cut_10
  - P_10